apiVersion: v1
kind: Service
metadata:
  name: schema-registry-svc
  namespace: kafka
spec:
  selector:
    app: schema-registry
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30092
    - name: https
      port: 8443
      targetPort: 8443
      nodePort: 30443
