apiVersion: v1
kind: Service
metadata:
  name: kafka-connect-svc
  namespace: kafka
spec:
  selector:
    app: kafka-connect
  type: NodePort
  ports:
    - port: 8083
      targetPort: 8083
      nodePort: 30099
